### ISSUE TITLE
【横須賀マップ #64】訓練実行エラーの修正

### ISSUE THREAD

**Issue by tsyu12345** [tsyu12345/Rikkyo-MasterPJ#68]
```
[ERROR] UnityEnvironment worker 0: environment raised an unexpected exception.
Traceback (most recent call last):
  File "C:\Users\syu\Products\Rikkyo-MasterPJ\.venv\lib\site-packages\mlagents\trainers\subprocess_env_manager.py", line 163, in worker
    env = env_factory(worker_id, side_channels)
  File "C:\Users\syu\Products\Rikkyo-MasterPJ\.venv\lib\site-packages\mlagents\trainers\learn.py", line 189, in create_unity_environment
    return UnityEnvironment(
  File "C:\Users\syu\Products\Rikkyo-MasterPJ\.venv\lib\site-packages\mlagents_envs\environment.py", line 242, in __init__
    if not UnityEnvironment._check_communication_compatibility(
  File "C:\Users\syu\Products\Rikkyo-MasterPJ\.venv\lib\site-packages\mlagents_envs\environment.py", line 96, in _check_communication_compatibility
    if unity_communicator_version.version[0] == 0:
AttributeError: 'StrictVersion' object has no attribute 'version'
```

**Comment by tsyu12345** [comment]
![Image](https://github.com/user-attachments/assets/7b2d2c8d-0426-4800-8bcd-7af726b114cc)

学習時のUnityログには出てないが、現状実行中に出るエラーはこれのみ。これが原因か？？

**Comment by tsyu12345** [comment]
環境のスタックログが出力
mlagents側との通信が切れるようになった....

```
2024-12-31 17:01:55 DEBUG [subprocess_env_manager.py:223] UnityEnvironment worker 0: environment stopping.
2024-12-31 17:01:55 DEBUG [subprocess_env_manager.py:237] UnityEnvironment worker 0 closing.
2024-12-31 17:01:55 DEBUG [subprocess_env_manager.py:240] UnityEnvironment worker 0 done.
2024-12-31 17:01:55 WARNING [subprocess_env_manager.py:320] Restarting worker[0] after 'The Unity environment took too long to respond. Make sure that :
         The environment does not need user interaction to launch
         The Agents' Behavior Parameters > Behavior Type is set to "Default"
         The environment and the Python interface have compatible versions.
         If you're running on a headless server without graphics support, turn off display by either passing --no-graphics option or build your Unity executable as server build.
```

**Comment by tsyu12345** [comment]
一旦 Unity環境実行時は解消。しかしexeビルド環境下で引き続き発生。

**Comment by tsyu12345** [comment]
> ![Image](https://private-user-images.githubusercontent.com/74717905/399295270-7b2d2c8d-0426-4800-8bcd-7af726b114cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4MzQ3MTEsIm5iZiI6MTczNTgzNDQxMSwicGF0aCI6Ii83NDcxNzkwNS8zOTkyOTUyNzAtN2IyZDJjOGQtMDQyNi00ODAwLThiY2QtN2FmNzI2YjExNGNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTAyVDE2MTMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4NDkzNjEzNzAyZmRhZDcxNzI2ZTlmNWE4MGQzMTBiMGUxZDhjOTg5MGU1ODIzYWQ1OWUxNWViM2ZkZTQzNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MJuygNxNGn9oMwvwTYd446TkSeabeo1pAM_zWGiKn7Y)
> 
> 学習時のUnityログには出てないが、現状実行中に出るエラーはこれのみ。これが原因か？？

上記は、手動でnullチェックを追加し封殺した。
- Master-Simulator\Library\PackageCache\com.unity.ai.navigation@2.0.5\Editor\NavigationOverlay.cs
```cs

void DisplayAgentPendingRequestWarningBox()
        {
            if (m_AgentPendingRequestWarning != null && !m_AgentPendingRequestWarning.visible)
            {

void HideAgentPendingRequestWarningBox()
        {
            if (m_AgentPendingRequestWarning != null && m_AgentPendingRequestWarning.visible)
            {
```

**Comment by tsyu12345** [comment]
現状コミットにて、Unity環境下での問題解消を確認。一旦クローズとする。
